experimental helper for tracking http requests
Utility class for collecting information about
an http request and response and updating metrics
as well as generating an access log message.

A helper function was added to Id for a common
case of adding a set of tags to an Id. This
does result in a compatibility change:

```
ERROR: com/netflix/spectator/api/Id.java: The
method withTags(java.lang.Iterable) has been added
Error count: 1
Warning count: 0
```

The baseline jar has been updated.

The RxHttp helper class was also updated to
use the new logging.