Avoid NPE if logEntry attribute isn't present (#1272)
Seeing this with e.g. an S3 client, where the original exception is getting
masked because the interceptor then emits an NPE:

```
java.lang.NullPointerException: Cannot invoke "com.netflix.spectator.ipc.IpcLogEntry.withException(java.lang.Throwable)" because "logEntry" is null
  at com.netflix.spectator.aws2.SpectatorExecutionInterceptor.onExecutionFailure(SpectatorExecutionInterceptor.java:204)
  at software.amazon.awssdk.core.interceptor.ExecutionInterceptorChain.lambda$onExecutionFailure$15(ExecutionInterceptorChain.java:194)
  at java.util.ArrayList.forEach(ArrayList.java:1596)
  at software.amazon.awssdk.core.interceptor.ExecutionInterceptorChain.onExecutionFailure(ExecutionInterceptorChain.java:194)
  at software.amazon.awssdk.core.internal.http.pipeline.stages.utils.ExceptionReportingUtils.reportFailureToInterceptors(ExceptionReportingUtils.java:41)
```

---------

Co-authored-by: Brian Harrington <brharrington@gmail.com>