add gauge overloads that take a ValueFunction
As part of the cleanup effort to finalize the API
`ValueFunction` was deprecated in favor of `ToDoubleFunction`
provided by the jdk. Since `ValueFunction` now extends
`ToDoubleFunction`, code registering a gauge with
a custom `ValueFunction` would compile fine. However
if you compiled with 0.29.x or earlier and tried running
with 0.30 you would get a NoSuchMethodError:

```
Exception in thread "main" java.lang.NoSuchMethodError: com.netflix.spectator.api.Registry.gauge(Ljava/lang/String;Ljava/lang/Object;Lcom/netflix/spectator/api/ValueFunction;)Ljava/lang/Object;
	at com.netflix.spectator.compat.Main.checkGauge(Main.java:151)
	at com.netflix.spectator.compat.Main.main(Main.java:184)
```

This change adds back overloads to `Registry` that
fix the binary compatibility issue and adds a test case
that uses a class compiled with a previous version.

We'll try to remove the deprecated methods and classes
before 1.0 if it can be done without too much havoc
internally.