fix auto bind plugin
Recent changes were causing the auto bind plugin
to fail with exceptions like:

```
2015-02-23 22:29:06,322 INFO  com.netflix.governator.guice.InternalAutoBindModule:187 [localhost-startStop-1] [bindAutoBindSingleton] Installing @AutoBindSingleton com.netflix.cag.client.AlertClientManager
java.lang.RuntimeException: com.google.inject.CreationException: Guice creation errors:

1) No implementation for com.netflix.spectator.http.ServerRegistry was bound.
  while locating com.netflix.spectator.http.ServerRegistry
    for parameter 0 at com.netflix.spectator.http.RxHttp.<init>(RxHttp.java:90)
  while locating com.netflix.spectator.http.RxHttp
    for parameter 0 at com.netflix.spectator.nflx.Plugin.<init>(Plugin.java:50)
  while locating com.netflix.spectator.nflx.Plugin
    for parameter 0 at com.netflix.spectator.nflx.AutoPlugin.<init>(AutoPlugin.java:31)
  at com.netflix.governator.guice.InternalAutoBindModule.getCurrentStackElement(InternalAutoBindModule.java:261)
```

This changes the auto bind to pull in the spectator
module rather than a separate singleton class. Also
removes the TestModule which prevented the test case
from failing with the same exception.