add type info to age functions
Avoids issues like:

```
error: type mismatch;
 found   : com.netflix.spectator.api.DoubleFunction[?0] where type ?0 <: Number
 required: java.util.function.ToDoubleFunction[Number]
Note: ?0 <: Number, but Java-defined trait ToDoubleFunction is invariant in type T.
You may wish to investigate a wildcard type such as `_ <: Number`. (SLS 3.2.10)
    "age", new AtomicLong(System.currentTimeMillis), Functions.AGE)
```