fix client used for subscription manager
Fix NPE if the client passed into the constructor is not
already set.

```
java.lang.NullPointerException: Cannot invoke "com.netflix.spectator.ipc.http.HttpClient.get(java.net.URI)" because "this.client" is null
        at com.netflix.spectator.atlas.SubscriptionManager.refresh(SubscriptionManager.java:81) ~[spectator-reg-atlas-0.128.0.jar:0.128.0]
        at com.netflix.spectator.atlas.AtlasRegistry.fetchSubscriptions(AtlasRegistry.java:452) ~[spectator-reg-atlas-0.128.0.jar:0.128.0]
        at com.netflix.spectator.impl.Scheduler$DelayedTask.runAndReschedule(Scheduler.java:401) ~[spectator-api-0.128.0.jar:0.128.0]
        at com.netflix.spectator.impl.Scheduler$Worker.lambda$run$0(Scheduler.java:475) ~[spectator-api-0.128.0.jar:0.128.0]
        at com.netflix.spectator.api.SwapTimer.record(SwapTimer.java:53) ~[spectator-api-0.128.0.jar:0.128.0]
        at com.netflix.spectator.impl.Scheduler$Worker.run(Scheduler.java:475) ~[spectator-api-0.128.0.jar:0.128.0]
        at java.lang.Thread.run(Thread.java:832) [?:?]
```